FROM php:7.3.4-apache-stretch

RUN useradd delain

COPY ./docker/apache2.conf /etc/apache2/apache2.conf
COPY ./docker/000-default.conf /etc/apache2/sites-available

RUN chown -R delain: /etc/apache2/sites-available && \
mkdir -p /usr/share/man/man1 && \
mkdir -p /usr/share/man/man7 && \
apt-get update && \
apt-get install -y libpq-dev libz-dev libmemcached-dev uuid-runtime git netcat postgresql-client && \
docker-php-ext-install pdo pdo_pgsql pgsql && \
pecl install memcached && \
docker-php-ext-enable memcached && \
a2enmod rewrite && \
apt-get clean && rm -rf /var/lib/apt/lists/*

