ALTER TABLE public.bonus_type
   ADD COLUMN tbonus_description character varying(1024);

UPDATE bonus_type SET tbonus_description='Régénération: Chaque point positif de Régénération augmente la Régénération au passage de DLT.' where tbonus_cod=10;
UPDATE bonus_type SET tbonus_description=NULL  where tbonus_cod=15;
UPDATE bonus_type SET tbonus_description=NULL  where tbonus_cod=17;
UPDATE bonus_type SET tbonus_description=NULL  where tbonus_cod=55;
UPDATE bonus_type SET tbonus_description='Bernardo: Si Bernardo présent parmi les B/M, impossible d''envoyer des messages par la Messagerie.' where tbonus_cod=2;
UPDATE bonus_type SET tbonus_description='Poison: Chaque point positif de Poison agit comme une Régénération négative (comme Combustion, Hémolyse et Venin), synergique avec le sort Hémophilie (comme Hémolyse et Venin).' where tbonus_cod=13;
UPDATE bonus_type SET tbonus_description='Ultrasons: Si Ultrason présent parmi les B/M, transforme un quart des caractères des messages reçus de la Messagerie.' where tbonus_cod=14;
UPDATE bonus_type SET tbonus_description=NULL  where tbonus_cod=19;
UPDATE bonus_type SET tbonus_description=NULL  where tbonus_cod=18;
UPDATE bonus_type SET tbonus_description=NULL  where tbonus_cod=56;
UPDATE bonus_type SET tbonus_description='Impotence: Si Impotence présent parmi les B/M, établit à un niveau bien inférieur le seuil de base des réussites spéciales, qui est initialement défini à 25 %.' where tbonus_cod=57;
UPDATE bonus_type SET tbonus_description=NULL  where tbonus_cod=1;
UPDATE bonus_type SET tbonus_description='Venin: Chaque point positif de Venin agit comme une Régénération négative (comme Combustion, Hémolyse et Poison), synergique avec le sort Hémophilie (comme Hémolyse et Poison).' where tbonus_cod=59;
UPDATE bonus_type SET tbonus_description='Désorientation: Les cibles des attaques physiques sont choisie aléatoirement parmi les cibles possibles, juste après la décision d''attaque du personnage. Les probabilités qu''une cible aléatoire soit choisie alors sont de 33% pour chaque point de Désorientation (compris de 1 à 3). Notamment conféré par le sort Morsure du soleil.' where tbonus_cod=60;
UPDATE bonus_type SET tbonus_description=NULL  where tbonus_cod=66;
UPDATE bonus_type SET tbonus_description='Fragilité: Chaque point positif de Fragilité diminue l''Armure.' where tbonus_cod=67;
UPDATE bonus_type SET tbonus_description='Force: Chaque point positif de Force augmente la Caractéristique Force.' where tbonus_cod=68;
UPDATE bonus_type SET tbonus_description='Intelligence: Chaque point positif de Intelligence augmente la Caractéristique Intelligence.' where tbonus_cod=69;
UPDATE bonus_type SET tbonus_description='Constitution: Chaque point positif de Constitution augmente la Caractéristique Constitution.' where tbonus_cod=71;
UPDATE bonus_type SET tbonus_description=NULL  where tbonus_cod=70;
UPDATE bonus_type SET tbonus_description=NULL  where tbonus_cod=26;
UPDATE bonus_type SET tbonus_description='Hortiphilie: Chaque point positif d''Hortiphilie diminue les PA requis pour la fabrication de Potions.' where tbonus_cod=65;
UPDATE bonus_type SET tbonus_description='Béni: Chaque point négatif de Bénédiction ajoute un bonus à tous les jets bruts des tests de Compétence.' where tbonus_cod=52;
UPDATE bonus_type SET tbonus_description='Maudit: Chaque point positif de Malédiction ajoute un malus à tous les jets bruts des tests de Compétence.' where tbonus_cod=53;
UPDATE bonus_type SET tbonus_description='Armure (Potion): Chaque point positif d''Endurcissement ajoute à l''Armure.' where tbonus_cod=39;
UPDATE bonus_type SET tbonus_description='PA/Déplacement: Chaque point négatif de Mobilité diminue le coût en PA d''un déplacement.' where tbonus_cod=3;
UPDATE bonus_type SET tbonus_description='Conscience flux de soin: Chaque point positif de Bienfaisance ajoute aux PV (jusqu''à PVmax) du lanceur de sorts de soins lors du lancé sur cible tièrce. Cet ajout aux PV est modifié par un facteur dépendant du sort de soin lancé. Implanté notamment par le sort Conscience des flux.' where tbonus_cod=47;
UPDATE bonus_type SET tbonus_description='Creusage (Potion): Chaque point positif de Creuser augmente la Compétence Creuser.' where tbonus_cod=24;
UPDATE bonus_type SET tbonus_description='Dégâts: Chaque point positif de Ravage ajoute aux Dégâts contact et distance.' where tbonus_cod=7;
UPDATE bonus_type SET tbonus_description='Défense magique: Si Rempart présent parmi les B/M, quasiment aucun sort ne peut affecter le bénéficiaire.' where tbonus_cod=44;
UPDATE bonus_type SET tbonus_description='Lenteur temporelle: Chaque point positif de Torpeur augmente le temps de tour (en minutes).' where tbonus_cod=49;
UPDATE bonus_type SET tbonus_description='Accélération temporelle: Chaque point positif d''Agitation diminue le temps de tour (en minutes).' where tbonus_cod=48;
UPDATE bonus_type SET tbonus_description='Danse de Saint Guy: Si Défense présent parmi les B/M, le modificateur de défense relatif aux modes de combat est augmenté.' where tbonus_cod=54;
UPDATE bonus_type SET tbonus_description='PA sort enchanteur runique: Chaque point négatif de Performance diminue le coût en PA des sorts de Voie des Enchanteur runique.' where tbonus_cod=45;
UPDATE bonus_type SET tbonus_description='Esquive: Chaque point positif d''Esquive augmente la Compétence Esquive.' where tbonus_cod=9;
UPDATE bonus_type SET tbonus_description='Fuite: Chaque point positif de Fuite augmente la Compétence Fuite.' where tbonus_cod=58;
UPDATE bonus_type SET tbonus_description='Brûlure profonde: Chaque point positif de Combustion agit comme une Régénération négative (comme Hémolyse, Poison et Venin).' where tbonus_cod=64;
UPDATE bonus_type SET tbonus_description='PA/Attaque: Chaque point négatif d''Ardeur diminue le coût en PA d''une attaque avec arme.' where tbonus_cod=5;
UPDATE bonus_type SET tbonus_description='PA/Sort: Chaque point négatif d''Alacrité diminue le coût en PA des sorts.' where tbonus_cod=11;
UPDATE bonus_type SET tbonus_description='Conservation des runes pour sort raté (Potion): Chaque point positif de Conservation modifie d''autant la valeur du dé, de base D100, du tirage de conservation de runes dans le cas d''un sort raté. Le tirage doit excéder 75 pour conserver 1 ou plusieurs runes.' where tbonus_cod=34;
UPDATE bonus_type SET tbonus_description='Malus lié à hypnotisme: Chaque point positif d''Hypnose diminue le nombre de PA disponible en début de tour.' where tbonus_cod=51;
UPDATE bonus_type SET tbonus_description='Maladie: Chaque point négatif d''Infection diminue la valeur de tout soin reçu ou régénération réalisée (jusqu''à une limite de 0).' where tbonus_cod=46;
UPDATE bonus_type SET tbonus_description='Bonus (%) sur lancement d’un sort (Potion): Chaque point positif de Magies augmente les Compétences de Magie de l''Esprit et Magie Hermétique.' where tbonus_cod=41;
UPDATE bonus_type SET tbonus_description='Maladie du sang: Chaque point positif d''Hémolyse agit comme une Régénération négative (comme Combustion, Poison et Venin), synergique avec le sort Hémophilie (comme Poison et Venin), notamment appliqué par le sort Transfert de pouvoir.' where tbonus_cod=63;
UPDATE bonus_type SET tbonus_description=NULL  where tbonus_cod=25;
UPDATE bonus_type SET tbonus_description='PA/Attaque (Potion): Chaque point négatif d''Impétuosité diminue le coût en PA d''une attaque avec arme.' where tbonus_cod=38;
UPDATE bonus_type SET tbonus_description='Vue (Potion): Chaque point positif de Perception augmente la Caractéristique Vue.' where tbonus_cod=20;
UPDATE bonus_type SET tbonus_description=NULL  where tbonus_cod=16;
UPDATE bonus_type SET tbonus_description='Compétence corps à corps (Potion): Chaque point positif de Corps-à-corps augmente les Compétences d''armes de contact.' where tbonus_cod=35;
UPDATE bonus_type SET tbonus_description='Dégâts corps à corps (Potion): Chaque point positif de Carnage ajoute aux Dégâts des armes de contact.' where tbonus_cod=36;
UPDATE bonus_type SET tbonus_description='Dégâts à distance (Potion): Chaque point positif de Perforation ajoute aux Dégâts des armes à distance.' where tbonus_cod=21;
UPDATE bonus_type SET tbonus_description='Bonus au toucher à distance (Potion): Chaque point positif de Distance augmente les Compétences d''armes à distance.' where tbonus_cod=22;
UPDATE bonus_type SET tbonus_description='Limite l’impact des blessures sur la DLT (Potion): Une valeur non nulle de Relaxation annule l''impact du malus de temps sur la DLT lié aux blessures.' where tbonus_cod=42;
UPDATE bonus_type SET tbonus_description='Vue: Chaque point positif de Vision ajoute à la distance de Vue.' where tbonus_cod=8;
UPDATE bonus_type SET tbonus_description='Armure: Chaque point positif de Carapace ajoute à l''Armure.' where tbonus_cod=4;
UPDATE bonus_type SET tbonus_description='Mur d''air: Chaque point positif d''Immatérialité augmente la Compétence d''Esquive.' where tbonus_cod=50;
UPDATE bonus_type SET tbonus_description='Régénération (Potion): Chaque point positif de Régénération augmente la Régénération au passage de DLT.' where tbonus_cod=37;
UPDATE bonus_type SET tbonus_description='Bloque magie: Chaque point positif de Bloque magie ajoute au Bonus à la Compétence Bloque magie. Il n''y a de blocage magique effectif que si la valeur de base de cette Compétence n''est pas nulle.' where tbonus_cod=12;
UPDATE bonus_type SET tbonus_description=NULL  where tbonus_cod=6;
UPDATE bonus_type SET tbonus_description='Asphyxie du garde manger: Chaque point négatif d''Asphyxie diminue les PV. Chaque tour passé du B/M actif diminue de 10 points l''Asphyxie.' where tbonus_cod=61;
UPDATE bonus_type SET tbonus_description=NULL  where tbonus_cod=72;
UPDATE bonus_type SET tbonus_description=NULL  where tbonus_cod=23;
UPDATE bonus_type SET tbonus_description='Malus d''esquive: Chaque point négatif de Balourdise diminue la Compétence Esquive. Effet notamment induit par le sort Berserker.' where tbonus_cod=62;
